server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true
server:
  port: 8082

spring:
  application:
    name: voting_system
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/db.changelog-master.yml
#  datasource:
#    url: jdbc:postgresql://localhost:5432/library
#    username: historyweed
#    password: pass
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
  datasource:
    url: jdbc:h2:file:./db
    username: sa
    password:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.PostgreSQLDialect
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
logging:
  level:
    root: WARN
    ru.iooko.votingapp: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
#    org.springframework.security: DEBUG