server:
  port: 8082

spring:
  application:
    name: voting_system
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/db.changelog-master.yml
#  datasource:
#    url: jdbc:postgresql://localhost:5432/library
#    username: historyweed
#    password: pass
  datasource:
    url: jdbc:h2:file:./db
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.PostgreSQLDialect
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true